version: '2'

services:
  nginx:
    build: nginx/
    restart: always
    volumes:
      - ./nginx/wordpress:/usr/share/nginx/html
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - "8080:80"
    networks:
      - docker_nginx
    depends_on:
      - db
    links:
      - php
  php:
    build: php/
    restart: always
    volumes:
      - ./nginx/wordpress:/usr/share/nginx/html
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    networks:
      - docker_nginx
    links:
      - db
  db:
    build: mysql/
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Str0ngPassw0rd
      MYSQL_DATABASE: website_db
      MYSQL_USER: website_user
      MYSQL_PASSWORD: Str0ngPassw0rd
    networks:
      - docker_nginx

networks:
  docker_nginx:
    driver: bridge
